### ISSUE TITLE
404 Not Found error for POST request 

### ISSUE THREAD

**Issue by tomslee** [SAP-samples/cloud-objectstore-java-sample#7]
HI developers. I must be doing something wrong, and I hope you can tell me what.
Here is my modified manifest.yaml:
```
---
applications:
- name: objectstore-sample-svc
  host: i826690-objectstore-sample-svc
  memory: 2G
  buildpack: https://github.com/cloudfoundry/java-buildpack.git
  path: target/objectstore-sample-1.0.0.jar
  services:
    - objectstore-service
```

Here is my application after deployment (cf a)

```
name                     requested state   processes           routes
objectstore-sample-svc   started           web:1/1, task:0/0   objectstore-sample-svc.cfapps.us21.hana.ondemand.com
```
And the route definition (cf routes):
```
space    host                     domain                          port   path   protocol   apps
Helium   objectstore-sample-svc   cfapps.us21.hana.ondemand.com                 http       objectstore-sample-svc
```
Using Postman, I try to POST to this URL:

    https://i826690-objectstore-sample-svc.cfapps.us21.hana.ondemand.com/objectstorage.svc/api/v1/storage/

But the response is "404 Not Found: Requested route ('i826690-objectstore-sample-svc.cfapps.us21.hana.ondemand.com') does not exist."

Any ideas please?
